# Generated by Django 5.0.1 on 2024-01-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokai', '0002_tokai'),
        ('tokai', '0003_delete_tokai'),
    ]

    operations = [
    ]
