# Generated by Django 5.0.1 on 2024-01-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokai', '0004_merge_0002_tokai_0003_delete_tokai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokai',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='files',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
